Data:
    CleanMVPs: "../Data/Cleaned/CleanMVPs.csv"
    MVPs_X: "../Data/Cleaned/MVPs_X.csv"
    MVPs_y: "../Data/Cleaned/MVPs_y.csv"

Test_Size:
    Standard: 0.22
    MVPs: 0.3

Random:
    State: 22

Transformers:
    Rank: "../Transformers/rank_pt.pkl"
    Share: "../Transformers/share_pt.pkl"
    Top3: "../Transformers/top3_pt.pkl"
    Top5: "../Transformers/top5_pt.pkl"
    MVPs: "../Transformers/mvps_pt.pkl"

Scalers:
    Rank: "../Scalers/rank_scaler.pkl"
    Share: "../Scalers/share_scaler.pkl"
    Top3: "../Scalers/top3_scaler.pkl"
    Top5: "../Scalers/top5_scaler.pkl"

Models:
    Rank: "../Models/rank_lr.pkl"
    Share: "../Models/share_lr.pkl"
    Top3: "../Models/top3_lr.pkl"
    Top5: "../Models/top5_lr.pkl"
    MVPs: "../Models/mvps_lr.pkl"